### ISSUE TITLE
Can't run vision example

### ISSUE THREAD

**Issue by aw1231** [neurokernel/neurokernel#43]
Hi. I think I set up everything right, but when I run the vision demo I get:
```
[ec2-user@ip-172-31-23-207 vision]$ python vision_demo.py
Process LPU-14:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/ec2-user/neurokernel/neurokernel/core.py", line 423, in run
    self.pre_run()
  File "/home/ec2-user/neurokernel/neurokernel/LPU/LPU.py", line 460, in pre_run
    self._initialize_gpu_ds()
  File "/home/ec2-user/neurokernel/neurokernel/LPU/LPU.py", line 598, in _initialize_gpu_ds
    np.float64)
  File "/usr/local/lib64/python2.7/site-packages/pycuda-2014.1-py2.7-linux-x86_64.egg/pycuda/gpuarray.py", line 939, in zeros
    result = GPUArray(shape, dtype, allocator, order=order)
  File "/usr/local/lib64/python2.7/site-packages/pycuda-2014.1-py2.7-linux-x86_64.egg/pycuda/gpuarray.py", line 199, in __init__
    self.gpudata = self.allocator(self.size * self.dtype.itemsize)
LogicError: cuMemAlloc failed: invalid context
[ec2-user@ip-172-31-23-207 vision]$
```

**Comment by lebedov** [comment]
I gather that you are using a Linux GPU instance on EC2. Can you check whether PyCUDA works properly, i.e., does the following run without any error?

```
import numpy as np
import pycuda.autoinit
import pycuda.gpuarray as gpuarray
x_gpu = gpuarray.to_gpu(np.arange(3))
```

**Comment by aw1231** [comment]
Yep. That works without errors.

**Comment by lebedov** [comment]
Are you using the latest revision of the master branch from GitHub?

**Comment by yiyin** [comment]
Hi, do you have two GPUs accessible on your instance? If not, please try the demo with
```
python vision_demo.py --lam_dev 0 --med_dev 0
```
This specifies to run both LPUs on GPU 0.

**Comment by aw1231** [comment]
@yiyin That worked.  Thanks!
